export const AUTH_ERROR_CODES = {
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  SESSION_INVALIDATED: "SESSION_INVALIDATED",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_AUDIENCE_INVALID: "TOKEN_AUDIENCE_INVALID",
  TOKEN_MISSING: "TOKEN_MISSING",
} as const;
